Attempt 2

diff --git a/Makefile.ci.toml b/Makefile.ci.toml
--- a/Makefile.ci.toml
+++ b/Makefile.ci.toml
@@ -391,7 +391,6 @@ run_task = { name = [
     "start-tikv",
     "test-kvs",
     "stop-tikv",
-    "sleep",
     "start-tikv",
     "test-api-integration",
     "stop-tikv",
@@ -471,11 +470,11 @@ script = """
 	echo "Installing TiKV playground..."
     ${HOME}/.tiup/bin/tiup install pd tikv playground
 	echo "Starting TiKV playground..."
-	nohup ${HOME}/.tiup/bin/tiup playground --mode tikv-slim --kv 1 --pd 1 --db 0 --ticdc 0 --tiflash 0 --without-monitor > /tmp/tiup.log &
+	nohup ${HOME}/.tiup/bin/tiup playground --mode tikv-slim --kv 1 --pd 1 --db 0 --ticdc 0 --tiflash 0 --without-monitor --tag "testing" > /tmp/tiup.log &
 	set +e
 	tries=0
-	echo "Waiting for TiKV playground to be ready..."
-	while [[ $tries -lt 10 ]]; do
+	echo "Waiting for TiKV playground to start..."
+	while [[ $tries -lt 5 ]]; do
 		sleep 5
 		echo "Displaying playground status..."
 		if ! ${HOME}/.tiup/bin/tiup playground display >/dev/null; then
@@ -484,7 +483,7 @@ script = """
 		fi
 		exit 0;
 	done
-	echo "PANIC: Couldn't start tiup playground! Here are the logs for the last attempt:"
+	echo "PANIC: Couldn't start TiKV playground! Here are the logs for the last attempt:"
     cat /tmp/tiup.log
     exit 1
 """
@@ -493,7 +492,23 @@ script = """
 category = "CI - SERVICES"
 script = """
     #!/bin/bash -ex
-    ${HOME}/.tiup/bin/tiup clean --all
+    echo "Cleaning TiKV playground..."
+    ${HOME}/.tiup/bin/tiup clean "testing"
+    set +e
+	tries=0
+	echo "Waiting for TiKV playground to stop..."
+	while [[ $tries -lt 5 ]]; do
+		sleep 5
+		echo "Displaying playground status..."
+		if ${HOME}/.tiup/bin/tiup playground display >/dev/null; then
+			tries=$((tries + 1));
+			continue
+		fi
+		exit 0;
+	done
+	echo "PANIC: Couldn't stop TiKV playground! Here are the logs for the last attempt:"
+    cat /tmp/tiup.log
+    exit 1
 """
 
 [tasks.clear-fdb]
@@ -507,11 +522,6 @@ args = [
     "--timeout",
     "20",
 ]
-
-[tasks.sleep]
-category = "CI - SERVICES"
-command = "sleep"
-args = ["30"]
 
 #
 # Builds
